# permissions for end users to edit helloapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helloapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: basa62-operator
    app.kubernetes.io/part-of: basa62-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloapp-editor-role
rules:
- apiGroups:
  - apps.basa62.com
  resources:
  - helloapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.basa62.com
  resources:
  - helloapps/status
  verbs:
  - get
